name: Mirror on .library changes

on:
  push:
    paths:
      - 'Library Repository/Beckhoff Automation LLC/**/*.library'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.email "admincarlen@cpmfgoperations.onmicrosoft.com"
          git config --global user.name "GitHub Actions Mirror"
          git config --global credential.helper store

      - name: Authenticate with Azure DevOps
        run: |
          # Use empty username and hardcoded PAT
          echo "https://user:9Ok7gieCPYSpTRcGpuWvTvJVLrwIqCPCja6peyq7nv4APSrcbJjqJQQJ99BAACAAAAArHd6SAAASAZDOD0ip@dev.azure.com" > ~/.git-credentials
          chmod 600 ~/.git-credentials

      - name: Mirror to Azure DevOps
        run: |
          mkdir -p mirror_workspace
          cd mirror_workspace

          # Clone using PAT directly in URL (alternative approach)
          git clone https://user:9Ok7gieCPYSpTRcGpuWvTvJVLrwIqCPCja6peyq7nv4APSrcbJjqJQQJ99BAACAAAAArHd6SAAASAZDOD0ip@dev.azure.com/CPMfgOperations/CP-Machine%20Building/_git/SPT-Libraries-Mirror target-repo
          cd target-repo

          # Add GitHub repo as remote
          git remote add github-origin "$GITHUB_WORKSPACE"

          # Fetch from GitHub
          git fetch github-origin --tags

          # Force push to Azure DevOps
          git push --mirror --force origin
