name: Mirror on .library changes

on:
  push:
    # Trigger the workflow when files under this folder (with .library extension) are changed.
    paths:
      - 'Library Repository/Beckhoff Automation LLC/**/*.library'
  workflow_dispatch:   # Enables manual triggering of the workflow

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@yourcompany.com"
          git config --global user.name "GitHub Actions Mirror"
          git config --global credential.helper store

      - name: Authenticate with Azure DevOps
        run: |
          echo "https://user:${AZDO_PAT}@dev.azure.com" > ~/.git-credentials
          chmod 600 ~/.git-credentials

      - name: Mirror to Azure DevOps
        env:
          AZDO_PAT: ${{ secrets.AZDO_PAT }}
        run: |
          # Create a temporary workspace
          mkdir -p mirror_workspace
          cd mirror_workspace

          # Clone the target Azure DevOps repository using the stored credentials
          git clone https://dev.azure.com/CPMfgOperations/CP-Machine%20Building/_git/SPT-Libraries-Mirror target-repo
          cd target-repo

          # Add the GitHub repository (checked out by Actions) as a remote.
          git remote add github-origin $GITHUB_WORKSPACE

          # Fetch all tags and branches from the GitHub remote.
          git fetch github-origin --tags

          # Mirror push to the target repository (be cautious: this overwrites all refs).
          git push --mirror --force origin

          # Optionally, preserve certain files (e.g., pipeline definitions) if they exist.
          if [ -f azure-pipelines.yml ]; then
            git checkout origin/main -- azure-pipelines.yml
            git commit -am "Preserve pipeline files" || echo "No changes to commit"
            git push origin main
          fi
